modLoader="javafml" 
loaderVersion="[31,)"
[[mods]]
    modId="bakadanmaku"
    version="${file.jarVersion}"
    displayName="Baka Danmaku"
    authors="TartaricAcid"
    description="A Live Danmaku Mod"